### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by kevinhaycock** [LaurentDardenne/ConvertForm#1]
Any Ideas

Got this error trying to install

> 
PackageManagement\Register-PackageSource : Module Repository 'OttoMatt' exists.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:4211 char:17
+ ...     $null = PackageManagement\Register-PackageSource @PSBoundParamete ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (Microsoft.Power...erPackageSource:RegisterPackageSource) [Register-Pack
   ageSource], Exception
    + FullyQualifiedErrorId : PackageSourceExists,Microsoft.PowerShell.PackageManagement.Cmdlets.RegisterPackageSource

Wow tried to post the output and git hub screws it, sorry for asking, I have no idea how to format the debug.

**Comment by kevinhaycock** [comment]
Ok managed to get it to work, jesus Microsh1t3 is crap

**Comment by LaurentDardenne** [comment]
Sorry to answer 2 years later, but I haven't received a notification :-/.
It was a test project, I now consider that Powershell is not the right tool to create GUIs.
