### ISSUE TITLE
New-ResourcesFile : Error (-1) during the generation of the resource file

### ISSUE THREAD

**Issue by mikemastercorp** [LaurentDardenne/ConvertForm#2]
During a conversion of WinForm app built with Visual Studio into a PowerShell code, I get the error when the project contains some included resources. So far I was not able to succeed on any of the computers I've tested a simple app with a single button and an image in it.

Seems like for some reason the project is converting properly, but the C# .resx file is not converted correctly. The full console error states:

```
PS C:\Users\Admin\Documents\Test-VS\Test> Convert-Form -Path "C:\Users\Admin\Documents\Test-VS\Test\Form1.Designer.cs"
New-ResourcesFile : Error (-1) during the generation of the resource file. Check the log file C:\Users\Admin\Documents\Test-VS\Test\Form1Properties.resources.log
At C:\Program Files\WindowsPowerShell\Modules\ConvertForm\2.0.0\ConvertForm.psm1:1022 char:7
+       New-ResourcesFile -Source $rsxSource -Destination $rsxDestinati ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-ResourcesFile
```

I am also attaching the log outpu
[Form1Properties.resources.log](https://github.com/LaurentDardenne/ConvertForm/files/7782239/Form1Properties.resources.log)
t

**Comment by LaurentDardenne** [comment]
Sorry to answer so late, but I did not receive a notification :-/.

The version of Resgen.exe is Visual Studio 2017 if I remember correctly. Without the code, it's hard to tell if it's my code that's the problem or the tool that's unsuitable.
I can only advise you, if you haven't already done so, to test with a more recent version of resgen.exe.
